services:
  chrome_automator:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: google-photos-downloader

    volumes:
      - /path/to/downloads:/downloads     # downloads go here
      - ./config:/tmp/gphotos-cdp  # chrome session goes here (created using docker-compose-login.yml)

    environment:
      # Set the sleep time in seconds (e.g., 6 hours = 21600)
      - WORKLOAD_SLEEP_DURATION=21600
      - WORKLOAD_INITIAL_DELAY=0

    # Set the entrypoint to our new wrapper script
    entrypoint: /app/scripts/app.sh

    shm_size: '1gb'

    cap_add:
      - SYS_ADMIN # Chome throws error re: namespace operations otherwise when starting session
